### ISSUE TITLE
Ability to download chapters in ascending order.

### ISSUE THREAD

**Issue by Beatsz** [xgi/houdoku#101]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Viewing the first chapter immediately after download, while the rest of the chapters are downloading consecutively in an ascending order would be really cool.
Currently the option. "Download > All" downloads in descending order. BUT the option. "Download > Next x Chapters" downloads in ascending order.

**Comment by xgi** [comment]
Fixed with #104 so downloads will be queued from lowest to highest chapter number. This is how it was supposed to work, must have missed it earlier. Thanks!
