### ISSUE TITLE
Error when opening A Manga

### ISSUE THREAD

**Issue by dragow0lf** [xgi/houdoku#108]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.0

### Operating system

Windows 10

### Steps to reproduce

- **First Step:** Install a extension that is either mangalife or mangasee
- **Second Step:** Search the webtoon "The beginning after the end" using either of the extensions
- **Third Step:** select the result "The beginning after the end"
- **Fourth Step:** The glitch is recreated, you get sent to an error page, this glitch as far as I have seen only applies to the beginning after the end. The same title has issues with all other sources it is available in as well, but those are different kinds of issues

### Expected behavior

The expected behavior: to get the popup that lets you add the title to your library

### Actual behavior

Actual behavior: You are sent to the error page that asks you to press Ctrl + R to reload or Ctrl + Shift + I to open up console for additional info

### Log files

[main.log](https://github.com/xgi/houdoku/files/8255823/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/8255825/renderer.log)

### Additional information

this issue only occurs with the beginning after the end on the mangalife and mangasee extensions. The same title has issues with other extensions its available in as well, but those issues are unrelated and/or in those cases is the extension's problem as the issue affects all manga, for example, anything in the mangakik extension stays on loading for ever or an extremely long time. In case of mangadex there isn't really any issue, just that the beginning after the end isn't available in english on there. When using the toonily extension for the beginning after the end, although the title is in english, it shows that the title is in korean and doesn't show up any chapters. When using isekaiscan you get into the same situation as when using toonily, where it shows that its in korean and hence doesn't show up any chapters when it actually is in english.

**Comment by xgi** [comment]
I've fixed this issue with the MangaSee/MangaLife extensions -- please update them to 1.1.2. Thanks!
