### ISSUE TITLE
[BUG] Cover image not loading when viewing in library

### ISSUE THREAD

**Issue by ramensensei** [xgi/houdoku#109]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

v2.8.0

### Operating system

Windows 7

### Steps to reproduce

1. Launched Houdoku on windows 7 laptop
2. [Issue] No cover image loaded
3. Browsing series in add series under different extensions
4. [Issue] No cover image 
[Uploading 2022-03-22 22-37-51.zip…]()
The following .zip file contains a video of the issue

### Expected behavior

It should load the cover image 

### Actual behavior

It is not loading the cover image

**Comment by ramensensei** [comment]
The same issue was raised earlier but the cover page was visible when opening a series and in this case it is not even after opening it

**Comment by xgi** [comment]
Your video link isn't working; can you reupload it somewhere or give an example of an extension + series that this is happening with?

**Comment by ramensensei** [comment]
It is happening with all extensions and series 
https://youtu.be/6SdU1g5dGbo (reuploaded video)

**Comment by xgi** [comment]
Thanks for the updated link. However I'm not able to reproduce this, so there may not be much I can do to debug the issue.

Something you can try is press `Ctrl+Shift+i` and go to the network tab, and then try to load the extension search results. It should show a bunch of requests for the cover images. If the requests are failing then it's likely an issue with your network. If the status is still 200 then it may be a Houdoku issue.
