### ISSUE TITLE
When reading a manga chapter, on opening the settings and changing settings only one page is displayed

### ISSUE THREAD

**Issue by logotie** [xgi/houdoku#13]
![2019-07-1612-56-49 (1)](https://user-images.githubusercontent.com/26583547/61292607-9addc100-a7c9-11e9-88e8-75ecf3694818.gif)

**Comment by xgi** [comment]
I noticed this only happened with some trackers, so I narrowed it down to some fields used to cache image urls not getting cleared. Should be fixed with 0ed8b9460f85ee6677c4f17a610982f5cd92e59a.

Thanks!
