### ISSUE TITLE
Being able to read the chapters in "webp" format

### ISSUE THREAD

**Issue by KasukeLp23** [xgi/houdoku#145]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.2

### Operating system

Windows 10

### Steps to reproduce

1. Adding the manga to the library
2. Start reading
3. No images appear (it remains in a loop)

### Expected behavior

Displays the images in that format

### Actual behavior

Does not show images

### Additional information (optional)

In **"jpg"** format it works perfectly
![image](https://user-images.githubusercontent.com/70596255/171409982-981d2b2b-ff12-4712-a586-29c5a4df9694.png)
But in **"webp"** format nothing appears
![image](https://user-images.githubusercontent.com/70596255/171410229-b6dc1e94-a537-4746-93ca-4cd6fdc2a38b.png)

**Comment by xgi** [comment]
Fixed with 21507af9566505a84334d165403bec240b26d655. Thanks!

**Comment by KasukeLp23** [comment]
@xgi Sorry, when will be the next update?
