### ISSUE TITLE
Bad Image/Page Quality

### ISSUE THREAD

**Issue by Expakun** [xgi/houdoku#150]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.2

### Operating system

Windows 11

### Steps to reproduce

1.  Open any Chapter of Any Manga
2. Compare the Quality of the pages to the pages of the original Website

### Expected behavior

It should look the same/the quality should be the same

### Actual behavior

The Quality of the pages is lower in the App than on the Website

### Additional information (optional)

I use Manga4Life and MangaDex
The Pages are Blurred and the Installer is so too

**Comment by Expakun** [comment]
Edit: It only happens if I use Fit Height

**Comment by ScruffiX** [comment]
Wouldn't really say this is a bug.
As you said it only happens when you adjust the picture to either height or width.
Obviously if you scale a picture it's gonna look differently than the original unadjusted picture.

**Comment by xgi** [comment]
I'm not able to reproduce an issue here.
