### ISSUE TITLE
Add mangakakalot extension

### ISSUE THREAD

**Issue by Herzheys** [xgi/houdoku#152]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Mangakakalot has the biggest library i have ever known and most of the manga apps i use have it and i think it would be natural for houdoku to have it

**Comment by xgi** [comment]
There is already a card open for this in the extensions repo: https://github.com/xgi/houdoku-extensions/issues/44
