### ISSUE TITLE
"Stretch to Fill" and "Fit Height" not working as intended

### ISSUE THREAD

**Issue by sayoohnara** [xgi/houdoku#158]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.9.0

### Operating system

Linux, EndeavourOS KDE

### Steps to reproduce

1. Open Houdoku in fullscreen mode
2. Open any library entry with small resolution images (lower than monitor resolution)
3. Select "Fit Height"
4. Toggling "Stretch to Fill" on

### Expected behavior

Selecting "Fit Height" and "Stretch to Fill" should leave no borders above or below the image. It is expected that the image uses up all vertical space.

### Actual behavior

Selecting "Fit Height" and "Stretch to Fill" does leave borders above and below the image.

### Additional information (optional)
1440p monitor in use.
Possible workaround: Ctrl + to zoom in the whole application. Bug occurs at default zoom
![image](https://user-images.githubusercontent.com/99587708/176636836-26f31950-8d92-43b1-b4a8-75f884350113.png)

**Comment by xgi** [comment]
Fixed with 38d1211b0b3f0adb1185e884c11a0bbd7a82fdab. Thanks!
