### ISSUE TITLE
Include manga thumbnail on discord rich presence

### ISSUE THREAD

**Issue by 6days9weeks** [xgi/houdoku#159]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Currently the rich presence looks like this when reading a manga, the large image being used there is houdoku's icon, but since discord allows you to use any image on large image now, if we use the manga thumbnail URL, it would show in the presence and houdoku's image could be used in small image key
<img width="293" alt="image" src="https://user-images.githubusercontent.com/60399731/176685461-261943df-9642-4eb0-8a54-a6192abc9858.png">

### Additional information (optional)

https://discord.com/developers/docs/topics/gateway#activity-object-activity-asset-image

**Comment by xgi** [comment]
Added with 6dd1366d5dba9b8a87548797597c64551703266f. Thanks!
