### ISSUE TITLE
Zoom on pages in reader

### ISSUE THREAD

**Issue by xgi** [xgi/houdoku#16]
Add support for zooming in on pages in the reader. Should support the typical ctrl +/- shortcuts, and there should be preset zoom levels in the menu to select from.

**Comment by bayang** [comment]
Hi, I pushed a branch called zoom in my fork repo, maybe if you have time you could try to have a look before I start a PR.

https://github.com/bayang/houdoku/commit/06b516f36c89e1ab617d13ed3cdb1fa1ef3ddcd7
