### ISSUE TITLE
App freezes

### ISSUE THREAD

**Issue by paulojsantos** [xgi/houdoku#164]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

 v2.9.1

### Operating system

Windows 10

### Steps to reproduce

1. Open the app
2. Open library tab
3. Choose any series
4. Hover cursor over Vol. or Ch. tab
5. App freezes.
6. Close the app.

### Expected behavior

It shouldn't freeze.

### Actual behavior

When I hover the cursor over Vol. or Ch. tab (see screenshot bellow) the app freezes.
![Houdoku_XhF9hzGJyM](https://user-images.githubusercontent.com/28137453/178151875-92fc1b4f-9542-4c68-adcf-f7b7230d66ed.png)

### Log files

[main.log](https://github.com/xgi/houdoku/files/9079357/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/9079358/renderer.log)

**Comment by Aiseku-q** [comment]
It seems like I can reproduce this bug by lowering my cpu freq(speed) to 1.50Ghz
Everything works fine after I put the cpu freq(speed) to 3.60Ghz

I used the control panel's power options to adjust the speed*
Could also be a multi-core or threading problem (Just my speculation)

Here's my specs and the adjusting of the cpu speed:

High performance
![image](https://user-images.githubusercontent.com/109046713/178165683-2fc97c3d-4b4a-4431-b359-7a65985540f4.png)


Low performance
![image](https://user-images.githubusercontent.com/109046713/178165703-75e583f1-674c-4c2e-8a83-1bc07685a01f.png)

**Comment by xgi** [comment]
This should be resolved with v2.9.2. Thanks!
