### ISSUE TITLE
Order of numbering | Number of chapters in title page

### ISSUE THREAD

**Issue by KasukeLp23** [xgi/houdoku#168]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

When you read a chapter of a title, both the order and the number of chapters are reset.

As I said before, I have no idea if it can be done but if it can it is appreciated.

1. When the reader returns to the main page, the chapter order resets.
1.1 You could go back to the start and that the order is not restarted.

2. The number of chapters on the main title page is also reset
    2.1 It could return to the start and that the chosen option is not restarted.

### Additional information (optional)

Case 1:

![image](https://user-images.githubusercontent.com/70596255/178314099-acbf395a-285f-4cdd-a74e-414c76255742.png)

Case 2:

![image](https://user-images.githubusercontent.com/70596255/178314173-795f906e-9863-47f3-a603-39501df849c6.png)

**Comment by xgi** [comment]
I'll be doing some updates soon related to how client state is persisted, so I'll include this feature while adding that. Thanks for the suggestion!

**Comment by KasukeLp23** [comment]
Thank you!
