### ISSUE TITLE
Windows Defender Message for Houdoku

### ISSUE THREAD

**Issue by AlmightyWings232** [xgi/houdoku#169]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.9.1

### Operating system

Windows 10

### Steps to reproduce

1. Run latest version of Houdoku

### Expected behavior

Should run the exe file

### Actual behavior

It says:
Windows protected your PC
Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.

Application: Houdoku-Setup-2.9.1.exe 
Publisher: Unknown publisher 

Video attached:

https://user-images.githubusercontent.com/44907494/178725174-4a54434d-68f6-418b-836f-dbe052ae190b.mp4

**Comment by xgi** [comment]
Yeah, I have a message about this here: https://houdoku.org/docs/known-issues/windows-smartscreen-warning

The only real way to solve this indefinitely is to have a signing certificate, which I'm not willing to pay for with this project.
