### ISSUE TITLE
Should be able to identify double page spreads

### ISSUE THREAD

**Issue by AlmightyWings232** [xgi/houdoku#171]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Should be able to identify double page spreads, so it can separate them on double page view. 

For example, in Chainsaw Man Chapter 98 (I used MangaSee) it shows the first single page on the right and the double page spread on the left leading to it essentially showing 3 pages. In this case, it wasn't a big issue since the double page spread is on the left but if the double page spread is on the right it leads to later pages in the chapter being on the wrong side. 

![Houdoku_Qu8FDv53uk](https://user-images.githubusercontent.com/44907494/178967783-00f8d158-b1aa-4c70-810b-a9c9bc75c912.png)

If you go on Bleach Chapter 521 (I used MangaSee, again) it shows the double page spread on the right, which leads to later pages being on the wrong side. 

![Bleach Double Page](https://user-images.githubusercontent.com/44907494/178972200-28abc1fe-c188-4fb4-87b2-a5e56a0a52ab.jpg)

Later pages in that chapter that should be on the left are on the right side, and vice versa. 

![Pages out of order](https://user-images.githubusercontent.com/44907494/178972546-0c93413e-6ce7-40dd-8c5b-dab116f022a7.jpg)

You can tell they're on the wrong side since there should be a white gap in the middle of the page if they're in the correct order. This page is in the correct order, since there's a white line through the middle:

![Pages in correct order](https://user-images.githubusercontent.com/44907494/178974435-e00e35c9-e83a-4bac-b862-af56665d6648.png)

Hopefully that all made sense, and apologise for the scruffy writing

**Comment by xgi** [comment]
I've added this with f94c918f5f3bcd6c4101f9412e96d6d2ae760bfe. Spread pages (identified as width > height) will always be displayed individually. I've also added an "Offset Double Spreads" reader setting which can be used to fix alignment issues when pages are expected to be on a particular side.

Thanks!
