### ISSUE TITLE
Set Custom Covers

### ISSUE THREAD

**Issue by PlumBlossoms13** [xgi/houdoku#173]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Customized covers

### Additional information (optional)

I read manga I have downloaded outside of the app in volumes (cbz format) and it includes the cover for each as the first page. Would it be possible to right click the image and set that image as the cover for the manga in the library?

**Comment by xgi** [comment]
When adding the series, you can specify the cover file:

![image](https://user-images.githubusercontent.com/13564230/180581316-12a35b8c-00e8-443f-adc0-691d67464ff5.png)

You can also change it for an existing imported series by clicking the "Edit Details" button at the top of the series' page (you may need to click Refresh after):

![image](https://user-images.githubusercontent.com/13564230/180581391-5bd868ef-bec0-44bb-8d8a-7731b8bb21f0.png)
