### ISSUE TITLE
Ability to change the tracker entry

### ISSUE THREAD

**Issue by 5evn** [xgi/houdoku#174]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

If a manga title does not correspond exactly with what entries the tracker provides, the entry title should be able to be changed

### Additional information (optional)

I don't know if i am explaining it clearly, but for example, I am reading One Piece - Digital Colored Comics, and AniList doesn't have a "... - Digital Colored Comics" entry, so I want to, just like tachiyomi does, changing the title so it matches with the One Piece entry.
![image](https://user-images.githubusercontent.com/93556953/179392287-be1e63b7-2e53-4d12-ac1d-f23655b35d9d.png)

**Comment by xgi** [comment]
With d44ef95aed0eac70fa6bea792a0df7f596052948 I've added a field to specify the series title when searching on a tracker. It looks like this:

![image](https://user-images.githubusercontent.com/13564230/180581108-07208c44-07b7-4f85-a3c3-0f7d45646745.png)
Thanks!
