### ISSUE TITLE
Discord rich presence does not display managa cover art

### ISSUE THREAD

**Issue by notohh** [xgi/houdoku#176]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.9.2

### Operating system

Windows 11

### Steps to reproduce

1. Open houdoku
2. Read any manga
3. Check rich presence
4. Cover art is not displayed

### Expected behavior

It should display the manga cover art

### Actual behavior

It does not display the manga cover art

### Log files

[renderer.log](https://github.com/xgi/houdoku/files/9163200/renderer.log)
[main.log](https://github.com/xgi/houdoku/files/9163201/main.log)

### Additional information (optional)

doubt logs will help here, but i've attached them just in case!
![Discord_Re77pWM4ue](https://user-images.githubusercontent.com/31116143/180327249-ffd95d45-39bf-4447-894a-f4ddb2b77c83.png)

**Comment by xgi** [comment]
Thanks for the logs- it seems MangaSee/MangaLife updated its cover image URL. I've updated those extensions to 1.2.1 which should fix this (you'll need to refresh the series). Thanks!

**Comment by notohh** [comment]
> Thanks for the logs- it seems MangaSee/MangaLife updated its cover image URL. I've updated those extensions to 1.2.1 which should fix this (you'll need to refresh the series). Thanks!

thanks for the quick fix!
