### ISSUE TITLE
Poor image quality when fitting by height/width vs. no limit

### ISSUE THREAD

**Issue by drcorg** [xgi/houdoku#186]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.9.3

### Operating system

Windows 11 

### Steps to reproduce

1. Open chapter of series
2. Choose fit by height/width option from menu bar

### Expected behavior

When viewing a chapter while fitting by height the clarity of the image should remain the same versus not fiting the image.

### Actual behavior

The actual fitted image in either direction is noticeably blurrier than the unfitted image, even when in fullscreen with the menu hidden.
![fit height](https://user-images.githubusercontent.com/24192718/186295383-e2a54439-53aa-4864-8aac-c99ac316b724.png)

![unfitted](https://user-images.githubusercontent.com/24192718/186295398-447a0306-84f8-4a65-a1f0-787b96f1fe80.png)

**Comment by xgi** [comment]
I'm not sure I agree with this being an issue. When fitting to height/width, the source image remains the same which means that more pixels (from the source image) are being compressed into a smaller space. There's no way around that, it's just how scaling works. If your window/monitor were larger, it would look the same as the "original" version.

There would be an issue if the aspect ratio was not being preserved (which would cause blurriness) but that doesn't seem to be happening here.

**Comment by drcorg** [comment]
I get why fitting it would necessarily be more compressed, but I think the scaling must have something off. For example, here's the same downloaded image in the same window size when viewed through the windows viewer vs houdoku. It's most obvious in the text

![scaling](https://user-images.githubusercontent.com/24192718/186596047-a8e6a2a7-f071-4c96-8893-3d7647eca446.png)

**Comment by xgi** [comment]
Thanks for the followup. I found that there is indeed a CSS rule for changing the rendering type (`image-rendering: -webkit-optimize-contrast`).  AFAICT most other web-based readers don't use this, and I don't think I'd want it enabled universally, but I'll add a setting for it. I tried it with the Berserk page you're referencing, and it does make the text more clear. Thanks!

**Comment by xgi** [comment]
4886a070fb63cf1c76ca23d653966c78e02f937a adds an "Optimize contrast" setting in the reader settings.
