### ISSUE TITLE
Add an Option to change columns size "Add Series" like in the Library

### ISSUE THREAD

**Issue by ImSIFO** [xgi/houdoku#187]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Add an Option to change columns size "Add Series" like in the Library

**Comment by xgi** [comment]
With 107dd2a44c82ca877965fb5565522fae03bd6054 the Add Series page will now use the same column# setting as the library. There are some other UI changes I'd like to do on the search page, but this is fine for now. Thanks!
