### ISSUE TITLE
Offset Double Spreads Keyboard Shortcut

### ISSUE THREAD

**Issue by Enduser-only** [xgi/houdoku#188]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

The newly added Offset Double Spreads feature is an excellent feature. It would greatly benefit from a re-bindable keyboard shortcut as it is very similar in function to currently available "Toggle Reading Direction" and "Toggle Page Style" shortcuts. Additionally, it could also be added to the menu bar.

**Comment by xgi** [comment]
b21ae074604838fd0b9a3b2cfd50be5ae140f93d adds a keybind for this (default `u`, can be changed) and a menu button that appears when on the Double style. Thanks!

**Comment by Enduser-only** [comment]
Thank you!
