### ISSUE TITLE
For some mangas new chapters are appearing at the very bottom, regardless the sorting option

### ISSUE THREAD

**Issue by MoLP5776** [xgi/houdoku#191]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.9.4

### Operating system

Windows 10

### Steps to reproduce

![Houdoku report 1](https://user-images.githubusercontent.com/64364797/189531831-417101fe-ca63-49b7-9323-edae091f5739.PNG)
For

### Expected behavior

Chapters should be in sorting order

### Actual behavior

Chapters appear at the very bottom of the list

### Log files

[main.log](https://github.com/xgi/houdoku/files/9542702/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/9542703/renderer.log)

**Comment by xgi** [comment]
This should be fixed with 2.10.0.
