### ISSUE TITLE
Esc or backspace causes an error in reader

### ISSUE THREAD

**Issue by bayang** [xgi/houdoku#199]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.10.1

### Operating system

Linux/Apimage

### Steps to reproduce

* open a comic or manga in the reader (material comes from komga extension)
* press esc or backspace

### Expected behavior

It should exit the reader

### Actual behavior

An eror screen is displayed

### Log files

[renderer.log](https://github.com/xgi/houdoku/files/9623845/renderer.log)

### Additional information (optional)

Logs are filled with : [error] TypeError: Cannot read properties of undefined (reading 'extensionId')

Error page : 
![Screenshot_20220922_102110](https://user-images.githubusercontent.com/11558944/191697328-952f5a42-1362-47b2-b651-86da58a20474.png)

**Comment by xgi** [comment]
This will be fixed with a change I made yesterday (601f486aa4eee2b88b46deb3075b2da180901255), thanks!
