### ISSUE TITLE
On library page, add an "unread chapters" badge to covers

### ISSUE THREAD

**Issue by xgi** [xgi/houdoku#2]
This will probably be a small text label in the cover's stackpane. See LayoutHelpers.createCoverContainer. Note that this method is also used to display covers on the search page, where it doesn't make sense to show these badges. We can probably just add a boolean "with_badge" parameter to this method to only show them on the library page.

**Comment by logotie** [comment]
I think I will take this one :)

**Comment by logotie** [comment]
Sorry about the delay, I should hopefully submit a PR for this in the evening
