### ISSUE TITLE
Page skipping and jittering

### ISSUE THREAD

**Issue by merlinmarijn** [xgi/houdoku#200]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.10.2

### Operating system

windows 10

### Steps to reproduce

1. Load chapter
2. scroll

### Expected behavior

it should have scrolled smoothly

### Actual behavior

it keeps popping downwards when scrolling down and found when scrolling up that it can get stuck to the top of a page and keep jittering back down so that the top of the page is back ontop.

### Log files

[main.log](https://github.com/xgi/houdoku/files/9644624/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/9644625/renderer.log)

### Additional information (optional)

I made some gifs from manga that are:

https://imgur.com/a/8kgqHLe

1. downloaded through other software and imported locally
2. downloaded through houdoku
3. not downloaden and streaming it via extension

**Comment by xgi** [comment]
I was able to reproduce this, thanks for the report. Will be making some adjustments to the long-strip mode for the next update.

**Comment by Theotherguy1223** [comment]
I am also having this issue, was wondering if there was an estimated time for a fix?

**Comment by xgi** [comment]
Fixed with 4d8bd775f9284b02a6bb90e915c718f103ea8e5d. Sorry for the delay, I was going to do a larger change but I'll settle with a hacky solution for now. Will publish release today/tomorrow. Thanks!
