### ISSUE TITLE
Library Cover Images Stretched/Wrong Size

### ISSUE THREAD

**Issue by Theotherguy1223** [xgi/houdoku#205]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.10.2

### Operating system

Windows 10 Pro

### Steps to reproduce

Add any series, in any way, Both manually Adding it, or from any Extension.

### Expected behavior

Cover Images would be the size/ratio as the file chosen or uploaded, just sized up or down to fit.

### Actual behavior

Cover Images are Actually stretched instead of keeping the aspect ratio of the image chosen.

### Additional information (optional)

Provided Images as an Example.
My monitor Size is 1440p (2560x1440, 16:9) but the same behavior happens on my 1080p Monitor, just not as noticeable.
The images Provided are a mix between cover images I uploaded, and cover images the program grabbed from a manga website.

For each, I grabbed the EXACT image it was using, either from the original site, or the file I uploaded myself, shown on the bottom row. So the bottom row of images is the exact file it is using for the cover image.
This issue also effects the individual Series Page, as shown.

![Cover Example](https://user-images.githubusercontent.com/12008758/197039006-ac656e2f-f5c7-4b33-b4c7-8c87a64ee2b1.png)
![Series Image Example](https://user-images.githubusercontent.com/12008758/197039350-bf41df90-e35d-483f-94e8-f8000e586365.png)

**Comment by Theotherguy1223** [comment]
Library cover images are no longer stretched, but they are now zoomed in, cutting off the top and bottom.
is this intentional?

**Comment by xgi** [comment]
Yes, the size of the "container" is based only on the # of columns and size of the window, and if the cover image doesn't match that aspect ratio, it is zoomed on the center until it fills the container.

**Comment by Theotherguy1223** [comment]
> Yes, the size of the "container" is based only on the # of columns and size of the window, and if the cover image doesn't match that aspect ratio, it is zoomed on the center until it fills the container.

AH, I see, that makes sense. But you can only have 8 columns at most, which is not quite enough to make the container the correct proportions. Is there a way to have more than 8?
