### ISSUE TITLE
Download button missing in the latest update

### ISSUE THREAD

**Issue by rollingmoai** [xgi/houdoku#207]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.10.3

### Operating system

Windows 11

### Steps to reproduce

- Download Houdoku and add a manga to the library

### Expected behavior

I found Houdoku through this [YouTube video](https://www.youtube.com/watch?v=r5HAE5pel7A), which supposedly has a button to download a few or all chapters:
![image](https://user-images.githubusercontent.com/75471378/197495469-3659105e-e64f-4082-b5e9-eb9d4b0d26c2.png)

### Actual behavior

It seems to be missing:
![image](https://user-images.githubusercontent.com/75471378/197495581-30fa4bf9-9dd6-4720-8a57-02f1011ee6cc.png)

### Additional information (optional)

I see the download button on the individual chapters, and the one from the context menu, but downloading the entire manga is what I want to do.

Related to https://github.com/xgi/houdoku/commit/5ba9ebc6abbcd9d680b4977c3bca1b136d5ccfdc
> This functionality will be re-added with a separate control on the page.

**Comment by reuspppp** [comment]
Seconded.

**Comment by Theotherguy1223** [comment]
There is a download button on the right side of each chapter.
Right click that download button.
![Download Example](https://user-images.githubusercontent.com/12008758/197683885-adcfc064-0006-46c0-b7cf-6b5046a3b618.png)

**Comment by rollingmoai** [comment]
> There is a download button on the right side of each chapter. Right click that download button. ![Download Example](https://user-images.githubusercontent.com/12008758/197683885-adcfc064-0006-46c0-b7cf-6b5046a3b618.png)
There is no "Download all" button

**Comment by merlinmarijn** [comment]
a download all button is much appreciated when you have to download multiple 100's of chapters for multiple manga's

**Comment by Theotherguy1223** [comment]
> a download all button is much appreciated when you have to download multiple 100's of chapters for multiple manga's

I may be in the minority here, and I apologize for misunderstanding, But since it is `Download next X`, you could just put 1000, and it would download all the chapters. That's what I've been doing.

I assumed removing the download all button was intentional, for this change, could be wrong.
My apologies.

**Comment by rollingmoai** [comment]
> I may be in the minority here, and I apologize for misunderstanding, But since it is `Download next X`, you could just put 1000, and it would download all the chapters. That's what I've been doing.

That is more of a workaround and it is better to just add a "Download all" button

**Comment by Malkierian** [comment]
![image](https://user-images.githubusercontent.com/774771/200422039-75c58227-abc6-4d42-b9f2-4a88a25f982c.png)
There's also this little space in the title bar of the chapter list that could be used to have a download all button, it's blank right now, just in case the download button above was removed because of functionality redundancy or UI space preservation.

**Comment by rollingmoai** [comment]
Related to https://github.com/xgi/houdoku/commit/5ba9ebc6abbcd9d680b4977c3bca1b136d5ccfdc
> This functionality will be re-added with a separate control on the page.
