### ISSUE TITLE
Going to the previous page should jump from first to the last page of the previous chapter

### ISSUE THREAD

**Issue by rollingmoai** [xgi/houdoku#209]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

If you are on the first page of a chapter and go to a previous page, you would jump to the first page of the previous chapter instead of the last page as if you jumped by an entire chapter instead. This is confusing and has often caused me to jump back by a few chapters accidentally.

Going to the previous page should jump from the first to the last page of the previous chapter for a consistent flow.

**Comment by reuspppp** [comment]
that would be a really useful feature, but I think the best would be to give the option to the reader, like with a checkbox in the option menu.
