### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by omodia** [xgi/houdoku#215]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

- Hide all the UI elements full screen mode.

**Comment by vy137** [comment]
![image](https://user-images.githubusercontent.com/117022936/214580797-40dbe3d5-87bc-4586-b014-79be392a6c07.png)

When in full-screen mode, it would be great if the last remaining GUI element, the toolbar at the top, were hidden until the user hovers near the top of the screen, where it normally is. Simpler yet, it disappearing is preferable to it being there in full-screen mode for a full full-screen experience.

**Comment by xgi** [comment]
You can hide the menu bar with `m` (in fullscreen or windowed), which I think is sufficient.
