### ISSUE TITLE
Zoom in and Zoom out

### ISSUE THREAD

**Issue by omodia** [xgi/houdoku#217]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

- Zoom in/out of images in reader using 'ctrl+mouse wheel up/down'.

### Additional information (optional)

- Same as zooming in and out while using browser.

**Comment by titan-19** [comment]
this the only serious problem on the app, with a zooming features it will be perfect.
