### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by omodia** [xgi/houdoku#229]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

A Portable Version Of The Application.

**Comment by rollingmoai** [comment]
Resolved in https://github.com/xgi/houdoku/commit/286327f12e733cca351f734e49cf1b7a0353aea0
