### ISSUE TITLE
Can't install the extension

### ISSUE THREAD

**Issue by axyay** [xgi/houdoku#238]
### Acknowledgements

- [x] Ensure that Houdoku is up-to-date (check the About tab).
- [x] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [x] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.11.0

### Operating system

windows 10

### Steps to reproduce

When I open the HOUDOCK，trying to install the extension, this window will pop up, and the extension cannot be installed,

<img width="362" alt="屏幕截图 2022-12-03 113033" src="https://user-images.githubusercontent.com/117839927/205420672-a024cd80-ff1c-4363-b43d-c77806feeb47.png">

### Expected behavior

Install Extension

### Actual behavior

Not Installing Extension

### Log files

[locales -.zip](https://github.com/xgi/houdoku/files/10145547/locales.-.zip)

**Comment by xgi** [comment]
This is a network issue, there's nothing to be done within Houdoku to resolve it.
