### ISSUE TITLE
Hide top bar when Fullscreen & gap between pages

### ISSUE THREAD

**Issue by Dwelerwen** [xgi/houdoku#240]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

So as title suggest I would really appreciate few more preferences settings in Reader options.

The features:
1.When in full-screen the top bar with settings/pages/chapters could be hidden
2.Double page reading mode has little gap between pages

**Comment by xgi** [comment]
1. You can hide the top bar with `m`, I don't think it's worth doing this by default.
2. With 94897dda8685f5d7cdfabd4de62b4911103e52ce I renamed the "long strip margin" setting to "spacing between pages", and it now applies to both Double and LongStrip reading modes.

Thanks!
