### ISSUE TITLE
Unable to download chapters when it contains part 2 pages.

### ISSUE THREAD

**Issue by merlinmarijn** [xgi/houdoku#243]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

v2.11.0

### Operating system

Windows 10

### Steps to reproduce

1. Find manga/manwha that includes .5 chapters
2. see if main chapter and part 2 chapter have the same chapter #
3. if you see duplicate chapter #
4. download
5. download pauses and wont download regardless of repressing the button

### Expected behavior

downloads chapters

### Actual behavior

When you download anything even just straight up a normal chapter 1, it tries to download, fails, pauses, and does nothing after.
even if you go into downloads and press the button to continue downloading it just tries, fails, removes chapter from download list but doesnt actually download anything.

![image](https://user-images.githubusercontent.com/18032411/210233491-e6ad5a7c-6f2c-4030-b473-9bc60c7e3a3e.png)
![image](https://user-images.githubusercontent.com/18032411/210233518-37ada2da-b804-4252-adda-706d180efbf9.png)

These image is taken from the specific series "Yuan Zun"

### Log files

[renderer.log](https://github.com/xgi/houdoku/files/10331680/renderer.log)
[renderer.old.log](https://github.com/xgi/houdoku/files/10331681/renderer.old.log)
[main.log](https://github.com/xgi/houdoku/files/10331682/main.log)
[main.old.log](https://github.com/xgi/houdoku/files/10331683/main.old.log)

**Comment by xgi** [comment]
I don't believe this was actually related to the .5 chapters, but rather an issue with some Madara-based extensions (including DisasterScans) where the image URL was being parsed incorrectly -- causing the downloader to fail.

I've pushed an update for the extensions (https://github.com/xgi/houdoku-extensions/commit/87d886e7d85e7588cee025b6cb75e62ea9c1c00a), please update your extensions and let me know if it still doesn't work.
