### ISSUE TITLE
Incorrect zoom when Windows scaling is used

### ISSUE THREAD

**Issue by PatrikHampel** [xgi/houdoku#255]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.11.0

### Operating system

Windows 11

### Steps to reproduce

1. Set Windows scaling to above 100% (e.g. I'm using 125% at 1440p)
2. Look at a panel that is not being fit (either "no limit" chosen or e.g. "fit by width" where the width of the panel doesn't exceed the width of the monitor)

### Expected behavior

The image should be scaled 1:1 to the display's resolution. When opened in e.g. ImageGlass, the image is correctly scaled and sharp.

### Actual behavior

The image is too zoomed in, resulting in a blurry look.

**Comment by cmhobbs** [comment]
This is still broken for me.  It seems to be related to this issue:  https://github.com/xgi/houdoku/issues/270

I'm using 200% scaling on a surface pro 7+ with windows 11.

**Comment by YelovSK** [comment]
> This is still broken for me. It seems to be related to this issue: #270
> 
> I'm using 200% scaling on a surface pro 7+ with windows 11.

Yes, the solution to the incorrect image scaling seemed to be to simply ignore the scaling across the entire application. So before the UI elements would comply with the Windows scaling, but the images would be blurry because they would not be scaled correctly. Now the images are rendered fine, but as a side-effect the application seems to ignore the scaling.
