### ISSUE TITLE
App lags everytime you do something with a manga after new update

### ISSUE THREAD

**Issue by MoLP5776** [xgi/houdoku#258]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.12.0

### Operating system

Windows 11

### Steps to reproduce

Doing anything with a manga, like opening the chapter overview or opening a chapter itself will take a long time to load.

### Expected behavior

Opening/closing a manga and reading a chapter should go off with a minimal amount of lag

### Actual behavior

Opening/Closing a manga is followed by a 20-25 second lag and opening a chapter is followed by a 10 second lag. Closing a chapter is followed by a 15 second lag.

### Log files

[main.old.log](https://github.com/xgi/houdoku/files/11064268/main.old.log)
[renderer.log](https://github.com/xgi/houdoku/files/11064269/renderer.log)
[renderer.old.log](https://github.com/xgi/houdoku/files/11064270/renderer.old.log)
[main.log](https://github.com/xgi/houdoku/files/11064272/main.log)

**Comment by merlinmarijn** [comment]
same lag, but sometimes it just lags for minutes on end, unuseable with this amount of lag, if there is a temp fix. LMK cause i need my manga XD

**Comment by merlinmarijn** [comment]
Same issue, i tried deleting my whole library from scratch (80 gigs) at the point of 10-12 gigs it once again becomes un-useable. even clicking on "download unread" even when its only a few chapters it gets stuck for atleast 20 seconds but even upto multiple minutes.
