### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by kens21** [xgi/houdoku#259]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.12.0

### Operating system

Windows 10

### Steps to reproduce

i click a manga

### Expected behavior

i should get to read

### Actual behavior

Error: ENOENT: no such file or directory, scandir 

### Log files

Error: ENOENT: no such file or directory, scandir 'C:\Users\Bartolome\AppData\Roaming\Houdoku\downloads' at Object.readdirSync (node:fs:1390:3) at Object.e.readdirSync (node:electron/js2c/asar_bundle:5:10830) at b (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:677596) at E (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:678556) at se (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:461343) at ka (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:1152935) at El (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:1209917) at bc (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:1198899) at vc (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:1198827) at gc (file:///E:/Houdoku/resources/app.asar/dist/renderer.prod.js:2:1198690)

### Additional information (optional)

please help

**Comment by drcorg** [comment]
Had the same error, fixed by simply creating the mentioned downloads folder

**Comment by kens21** [comment]
> Had the same error, fixed by simply creating the mentioned downloads folder

im new at this i dont know how to fix this

**Comment by kens21** [comment]
> Had the same error, fixed by simply creating the mentioned downloads folder

thank you

**Comment by dubzuul** [comment]
> Had the same error, fixed by simply creating the mentioned downloads folder

how do you do that

**Comment by kens21** [comment]
> > Had the same error, fixed by simply creating the mentioned downloads folder
> 
> how do you do that
you just put a new file and rename it downloads
