### ISSUE TITLE
Unable to batch (Or Multiple) download a manga

### ISSUE THREAD

**Issue by 40yushaa** [xgi/houdoku#284]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.12.2

### Operating system

Windows 11

### Steps to reproduce

when i add a manga from any extension and try to download the whole manga for offline read, it won't download the manga. Please fix this issue asap because overall, I love this app

### Expected behavior

whole manga should batch download when i click "Download All" option

### Actual behavior

nothing happening when i click download all. but i can download one chapter at a time which is very painful

**Comment by dodumosu** [comment]
please close as xgi/houdoku#269 covers it, and the issue has been fixed (at least in the source)
