### ISSUE TITLE
Add a Font Size option.

### ISSUE THREAD

**Issue by trueauracoral** [xgi/houdoku#292]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

In the settings there should be an option to increase/decrease font size. 

### Additional information (optional)

I installed houdoku on windows and the font size is ridiculously small. I can read it but in order to not strain my eyes I want to make it a bit bigger.
![image](https://github.com/xgi/houdoku/assets/87541524/5f3e5a30-06fd-4449-b2a9-dca7cd575e97)

The screnshot compares the font size on github vs houdoku's font size. The font size on the houdoku window is so much smaller than the text on github.

**Comment by xgi** [comment]
There aren't discrete text scaling options, but `ctrl-shift-plus`, `ctrl-minus`, and `ctrl-0` can be used to scale the UI which imo is sufficient.
