### ISSUE TITLE
Cant Remove Series from library

### ISSUE THREAD

**Issue by grassy345** [xgi/houdoku#294]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.13.0

### Operating system

Linux Mint Cinnamon

### Steps to reproduce

Just go to any manga in your library, press options on top right corner and click remove series

### Expected behavior

It should remove the manga from the library

### Actual behavior

Instead it prompts you to download chapters of the manga.

**Comment by AlmightyWings232** [comment]
Same issue for me, on windows 10

**Comment by grassy345** [comment]
> Same issue for me, on windows 10

for now, you can go the library, right click the series you want to remove and click "remove" option.
