### ISSUE TITLE
Mark previous as read feature

### ISSUE THREAD

**Issue by AlmightyWings232** [xgi/houdoku#300]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Have a 'mark previous as read' feature like in Tachiyomi where you can mark every chapter before a selected chapter as read

**Comment by merlinmarijn** [comment]
already exists if you right click a chapter on the detail page 
![image](https://github.com/xgi/houdoku/assets/18032411/8382ee46-903f-4e9e-84ca-fe159072a11b)

**Comment by AlmightyWings232** [comment]
Man I feel stupid, I tried clicking and holding it but didn't think about right clicking 🤦‍♂️

Thank you tho!
