### ISSUE TITLE
Unable to delete a series, wrong option is executed when pressing it

### ISSUE THREAD

**Issue by BEP0P** [xgi/houdoku#304]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.13.00

### Operating system

Windows 10

### Steps to reproduce

1-Add a series either from an extension or a filesystem
2-try to remove the series
3-wrong message pops up

### Expected behavior

it should have said are you sure you want to delete this series!?

### Actual behavior

it actually said download chapters 
![image](https://github.com/xgi/houdoku/assets/117948649/fc69bc83-da48-4135-9be8-419f1d48456e)

### Log files

[renderer.log](https://github.com/xgi/houdoku/files/12753024/renderer.log)
[main.log](https://github.com/xgi/houdoku/files/12753025/main.log)

**Comment by xgi** [comment]
Fixed with #296
