### ISSUE TITLE
Cannot refresh or add new series.

### ISSUE THREAD

**Issue by TheMadog24** [xgi/houdoku#327]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.14.0

### Operating system

Windows 11

### Steps to reproduce

Update to v2.14.0 and install the Tiyo extension.

### Expected behavior

I would be able to add new series, or update existing series that I already have added.

### Actual behavior

None of my series are able to be refreshed or updated, and I cannot add new series from almost any site. Everytime you open or reload it, it gives the same error, "Library Refreshed with errors" and it lists every (non filesystem) series I have.

I have series from Manganato, Mangakakalot and Mangakik, none of these work now, I cannot add any series from any of these site, or any other sites I have tried. The only site that works is MangaDex, but I do not use MangaDex.

When I try to add a series from Manganato or Mangakakalot, I can see all of the series, and the search works, however, you cannot add any series, because it infinity says "Loading series details" when you click on any of them.

When trying to add a series from Mangakik, the page is just blank and no series are listed.

Sites for Reference:
https://manganato.com
https://mangakakalot.com
https://mangakik.org/

### Log files

[main.log](https://github.com/xgi/houdoku/files/13978490/main.log)
[main.old.log](https://github.com/xgi/houdoku/files/13978507/main.old.log)
[renderer.log](https://github.com/xgi/houdoku/files/13978496/renderer.log)

### Additional information (optional)

I was not sure if I should add this issue here or on the new Tiya Page, Apologies if this doesn't belong here.
Everything was working fine with the old extensions before updating.

EDIT:
I should add, any chapters that were already added (including chapters that were/are not downloaded) still work, and can still be read. Including chapters I have not read yet (in case indexing/caching are a thing), it is only adding/refreshing series from any of those 3 sites that do not work.

**Comment by xgi** [comment]
covered with https://github.com/xgi/tiyo/issues/2
