### ISSUE TITLE
Refreshing does not remove the deleted directory from the chapters list

### ISSUE THREAD

**Issue by maisans-maid** [xgi/houdoku#33]
App just loads indefinitely, and only shows the error on the console -> 
`Uncaught (in promise) Error: Error invoking remote method 'extension-getPageRequesterData': Error: ENOENT: no such file or directory, scandir 'C:\Users\<USER>\Documents\Houdoku\Hatsukoi Zombie\[c1]'`

**Comment by xgi** [comment]
Fixed with #37. Will verify with next release before closing.

Thanks for the report!
