### ISSUE TITLE
Light Theme is gone?

### ISSUE THREAD

**Issue by dtantono** [xgi/houdoku#331]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

21.14

### Operating system

Windows and Linux

### Steps to reproduce

1. open the app
2. go to Settings
3. it shows nothing to change the theme

### Expected behavior

According to this https://github.com/xgi/houdoku/issues/261 we can change the theme easily

### Actual behavior

it shows nothing

**Comment by xgi** [comment]
Reopened #261. A related PR was merged, but it still requires more work, so the light mode was never actually available.
