### ISSUE TITLE
Metadata is lost after refresh.

### ISSUE THREAD

**Issue by maisans-maid** [xgi/houdoku#34]
Before refresh
![image](https://user-images.githubusercontent.com/56829176/120112496-aad9d080-c1a8-11eb-98ca-120411a9703a.png)

After refresh
![image](https://user-images.githubusercontent.com/56829176/120112504-b6c59280-c1a8-11eb-89b8-01ebdd5653a0.png)

**Comment by xgi** [comment]
Fixed with #36. Will verify with next release before closing.

I think this regressed when the filesystem extension ID was changed. Thanks for the report!
