### ISSUE TITLE
Reader shortcuts not working as intended

### ISSUE THREAD

**Issue by BaccanoMob** [xgi/houdoku#38]
"[" and "]" = they do not seem to work at all 
"ctrl + <-" and "ctrl + ->" = both works only as to move to first page while no shortcut for last page

rest of them works as intended. Also personally I would prefer:
"ctrl + <-" and "ctrl + ->" as previous and next chapter so its easier to change without looking at the keyboard to find [ and ]
and "[" and "]" as first and last page shortcut.

It would also helpful if there is an option to automatically switch chapters to next upon reading the last page.

**Comment by xgi** [comment]
This was fixed a little while ago (including automatically switching chapters). I'll verify it's working before the next release to close this issue. Thanks!
