### ISSUE TITLE
An option to edit the series

### ISSUE THREAD

**Issue by BaccanoMob** [xgi/houdoku#39]
while there is an option to remove and refresh the series
![image](https://user-images.githubusercontent.com/82655889/120895071-aafc2500-c61b-11eb-8a6b-3f50cc560a7a.png)

It be cool to have an "Edit Series" option to make changes after adding a series rather than removing and re adding.

**Comment by BaccanoMob** [comment]
Also changing titles are impossible even in "add series" option. For example,
![image](https://user-images.githubusercontent.com/82655889/120896780-40e77e00-c623-11eb-81ba-a9e58541a10e.png)

This series got stuck with "I" and i can not rename it but I can edit other fields below. I tried restarting the app and try again but the result was still the same with "I" only. Also noticed some series the title gets half eaten in the "Add series" option.

**Comment by xgi** [comment]
The title editing is a recently-fixed bug. I definitely want to support editing a series, but I probably can't get to it soon. Thanks!
