### ISSUE TITLE
Last read title shown when series opened and continue reading option

### ISSUE THREAD

**Issue by BaccanoMob** [xgi/houdoku#44]
Currently it shows the latest chapter on top. Is it possible to show the initial page with the last read title?

This would make it easier to choose the last read title.

Also, preferable to have a "continue reading" button to automatically open the last read (not the next unread as opening any chapter results as read)

**Comment by xgi** [comment]
I'm not sure what "last read title" means -- do you mean having the most recently read chapter appear at the top of the list? I do want to add a "continue reading" button, though; there were some technical challenges last I checked, but I can revisit it.

**Comment by BaccanoMob** [comment]
Right now, if i open a series it shows the latest chapter on top, like this

![image](https://user-images.githubusercontent.com/82655889/121840960-a8fe2a00-ccdd-11eb-9d2b-38e7790daa3b.png)

since continue reading is not implemented, it would be easier to open if it automatically opens the page with the last read title (or a page with 1 or more tick marks but less than max), like this
![image](https://user-images.githubusercontent.com/82655889/121841107-f8445a80-ccdd-11eb-917a-1225ba348038.png)

But i guess it has more or less the same technical challenges as continue reading.

**Comment by xgi** [comment]
I've added a "Continue" button to the chapter table, which opens the next unread chapter. I think this alleviates the need to open to a specific page. Thanks!

![ex](https://i.imgur.com/3nUOu2i.png)
