### ISSUE TITLE
Decimal chapter are rounded off

### ISSUE THREAD

**Issue by BaccanoMob** [xgi/houdoku#46]
Decimal chapters are considered as an alternate chapter. It is not possible to open from the reader. Due to that it skips a chapter while reading continuously in the reader unless manually opened. 

![image](https://user-images.githubusercontent.com/82655889/121954617-42215500-cd5f-11eb-9145-6705511a2249.png)

**Comment by xgi** [comment]
I believe this was fixed with 2.1.0. You may be running an outdated version.
