### ISSUE TITLE
Right-to-left page scrolling

### ISSUE THREAD

**Issue by xgi** [xgi/houdoku#5]
Add a setting for inverting the direction pages are read, mimicking how real manga works. i.e., the page counter increases when going left.

A simple way to do this would probably be to change the "previousPage", "nextPage" buttons to be "leftPage" and "rightPage" and have their actions be determined by the direction setting.

**Comment by logotie** [comment]
I think I will take this one on

**Comment by logotie** [comment]
Hmmm, so
On pressing the left key it would proceed to the next page
On pressing the right key it would proceed to the previous page

**Comment by sbstratos79** [comment]
Isn't it already possible?
![image](https://user-images.githubusercontent.com/4395586/61291171-582ce080-a7eb-11e9-8e2c-3816d676283c.png)
