### ISSUE TITLE
Concerns with the recent version of the app [v2.2.0]

### ISSUE THREAD

**Issue by maisans-maid** [xgi/houdoku#53]
1. IDK but the app, when opened, just stays on the indefinite reloading library status [been going for nearly half an hour now]. Checking the Developer tools, i'm seeing this error.
![image](https://user-images.githubusercontent.com/56829176/124109665-fcbc9180-da99-11eb-95f9-c173917d7a7a.png)

2. The app has no height/width limit. You can actually do this [which i think, is a bad idea, i suggest having a width/height limit of atleast 800x600 pixels]. Actual shot of the app in limitless width/height below:
![image](https://user-images.githubusercontent.com/56829176/124110022-5cb33800-da9a-11eb-9da6-4083fb4b07f3.png)

3. Tied with the second concern, the preview image is dependent on the app width. The preview size becomes smaller the less the width the app has. And because currently it has no height/width limit, you can possibly render the app invisible. I suggest the preview image has its set size and changing width makes the overflow element move to the next row instead.
![image](https://user-images.githubusercontent.com/56829176/124110754-21fdcf80-da9b-11eb-8541-ca8075cead45.png)

4. Connected with the first concern, when you click the manga while the app says reloading library, you get this blank pink screen on the app. Basically, I cannot use the app now. I think removing the series and adding it back in would solve the issue, tho I haven't tried it yet.
![image](https://user-images.githubusercontent.com/56829176/124111053-72752d00-da9b-11eb-8253-4b7d4006b967.png)
Checking the developer tools gives me this error:
![image](https://user-images.githubusercontent.com/56829176/124111183-989acd00-da9b-11eb-93fc-c0ed41de156b.png)

**Comment by maisans-maid** [comment]
Turns out there is no way to remove the series outside its dedicated page. Now i'm stuck lol.

**Comment by xgi** [comment]
> 
> 
> ~Turns out there is no way to remove the series outside its dedicated page. Now i'm stuck lol.~
> 
> Edit:
> ~I went to the settings and disabled the refresh library on startup option. Now i can...~
> 
> Edit:
> No, clicking the entry still redirects me to that blank pink page, with the same error. Guess im stuck untill an update/fix becomes live.

I'm still looking into the cause, but there should be a way to manually delete the series for now: you should still be able to open the console with `ctrl+shift+i`. Go to the Application tab, and then expand the "IndexedDB" entry on the left (under the storage header) and click on the "series" table. You'll need to find the series in this list and right click -> delete. Restart the client after doing this.

![](https://i.imgur.com/tDaDxgZ.png)

**Comment by xgi** [comment]
>   1. IDK but the app, when opened, just stays on the indefinite reloading library status [been going for nearly half an hour now]. Checking the Developer tools, i'm seeing this error.

I was not able to reproduce this, but I believe it was caused from an earlier version update which changed how some series metadata was stored. #54 adds a failsafe that should avoid the error, but if this occurs the chapter list will appear empty until you delete/re-add the series.

>   2. The app has no height/width limit. You can actually do this [which i think, is a bad idea, i suggest having a width/height limit of atleast 800x600 pixels]. Actual shot of the app in limitless width/height below:

I've added a very minimal limit with #54 so the app name and minimize/close controls are always shown, but otherwise I don't really feel a need to limit the size as long as it doesn't cause crashes. Obviously I wouldn't use it past a certain point myself, but I don't think it needs to be enforced.

>   3. Tied with the second concern, the preview image is dependent on the app width. The preview size becomes smaller the less the width the app has. And because currently it has no height/width limit, you can possibly render the app invisible. I suggest the preview image has its set size and changing width makes the overflow element move to the next row instead.

You can change the number of series per row with the "columns" button at the top. The minimum is 2, but I think that's sufficient for most people.

>   4. Connected with the first concern, when you click the manga while the app says reloading library, you get this blank pink screen on the app. Basically, I cannot use the app now. I think removing the series and adding it back in would solve the issue, tho I haven't tried it yet.

I wasn't able to reproduce an error just by clicking on a series while its reloading, so I believe this was just a byproduct of the reload error for the series itself.
