### ISSUE TITLE
The manga is blank

### ISSUE THREAD

**Issue by kiraaaaii** [xgi/houdoku#58]
I was using houdoku and was testing it because it has anilist support for pc and I had this problem when I was reading Record of Ragnarok it just changes into a pink screen and I tried reinstalling but it didn't solve the issue.
https://user-images.githubusercontent.com/86195433/128304087-859c97e9-3dbd-4b66-a742-a9471a311ea3.mp4

**Comment by xgi** [comment]
If you press `ctrl+shift+i` when that pink screen shows up and go to the "Console" tab, there should be an error message -- can you post that here? Alternatively (shouldn't be required) you can upload your log files from the `C:\Users\<username>\AppData\Roaming\Houdoku\logs` folder.

Also, somewhat unrelated, I'll fix the bug making the title get parsed as just "Re".

**Comment by kiraaaaii** [comment]
![image](https://user-images.githubusercontent.com/86195433/128491597-e7d975b6-2901-46a5-9c9a-e9c451ae24b3.png)
This is the error message.

**Comment by kiraaaaii** [comment]
[main.log](https://github.com/xgi/houdoku/files/6944685/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/6944686/renderer.log)
These are the logs.

**Comment by xgi** [comment]
This is fixed with #59. The issue was one or more of the series properties didn't get set properly, so there was an error when trying to display them. I've also fixed the series title getting parsed incorrectly.

Thanks for posting the logs!
