### ISSUE TITLE
How to download manga in Houdoku?

### ISSUE THREAD

**Issue by kiraaaaii** [xgi/houdoku#60]
I am currently finding a manga reader with a built-in manga downloader so I think houdoku is the best on for it and I don't know how to download manga in houdoku.

**Comment by xgi** [comment]
You can download chapters by right clicking the tables of chapters on a series page and selecting Download/Download Previous/Download All. You can see what chapters are downloaded by going to the Downloads tab on the left and clicking "My Downloads" -- this will also show you the folder they got downloaded to.

However keep in mind the folder names will use Houdoku's id numbers, not the actual series/chapter titles.
