### ISSUE TITLE
Anilist tracking

### ISSUE THREAD

**Issue by Razi1660** [xgi/houdoku#62]
It would be nice if it updated your list when you finish a chapter rather than when you start a chapter (or at least have a option for this).

**Comment by xgi** [comment]
This might have similar implementation difficulties as in #63, but I can see the value. My concern originally was that I expect people to sometimes exit/go to the next chapter before going through all the pages (i.e. if there's an author interview at the end they don't want to read) where they would still want the chapter to be marked as read both in Houdoku and AniList. Can probably add some logic for it, but it's not straightforward imo.

**Comment by xgi** [comment]
With #74, chapters will only be marked as read and tracker lists will only be updated after getting past a certain page -- currently 80%, rounded down. I may add a setting for that amount later on, but I think this will be helpful for now. Thanks!
