### ISSUE TITLE
Custom download directory

### ISSUE THREAD

**Issue by kiraaaaii** [xgi/houdoku#66]
When downloading manga I think it's better if we can change where to download the chapters and change the title of the downloaded chapters.

**Comment by xgi** [comment]
I can probably add a setting for the download location. However, I'm not sure it's feasible to allow customizing the names of the chapter/series directories, since they need to be locate-able by their internal id.

**Comment by camiflappy** [comment]
At least as of the title, I would be on board, as I have installed Houdoku on an SSD, and would like it to offload all the downloads on to another hdd on my system.

Would it be possible to just be able to change directory? I dont mind it keeping its file/name structure.

If I should open another issue request, let me know.

**Comment by xgi** [comment]
Changing the download directory is added with v2.5.0. Thanks!
