### ISSUE TITLE
The keybinds are not working properly

### ISSUE THREAD

**Issue by kiraaaaii** [xgi/houdoku#72]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.5

### Operating system

Windows 10

### Expected behavior

It should move to the next chapter/previous.

### Actual behavior

When using houdoku I use the default keybinds to go to the next chapter but when I updated houdoku into the latest version The keybinds aren't working properly. When i press ] it doesn't move to the next chapter instead it reloads the chapter and the when I press esc it also doesn't work properly I also changed the keybinds but still nothing changes.

### Log files

[main.log](https://github.com/xgi/houdoku/files/7090315/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/7090316/renderer.log)

**Comment by xgi** [comment]
Fixed with #73. Thanks!
