### ISSUE TITLE
The download directory resets if you close Houdoku

### ISSUE THREAD

**Issue by kiraaaaii** [xgi/houdoku#76]
### Acknowledgements

- [X] Check the documentation on [houdoku.org](https://houdoku.org).
- [X] Check that there is not an existing ticket for this question, and that it is not related to an existing ticket.
- [X] If you aren't sure whether something is a bug, create a bug report anyway (instead of using this form).
- [X] Write a concise title for this ticket in the field above.

### Question type

- [X] Using Houdoku
- [X] Clarification on existing documentation
- [X] Development
- [ ] Other

### What is your question?

The download directory resets when closing it is it a bug or did you made it that way?

**Comment by xgi** [comment]
Whoops... this was a bug, fixed with a9b829d69a434f81fc8cfcaceae8f5a70feb1653. Thanks!
