### ISSUE TITLE
Downloaded chapters are not in order when reading offline.

### ISSUE THREAD

**Issue by kiraaaaii** [xgi/houdoku#77]
### Acknowledgements

- [X] Check the documentation on [houdoku.org](https://houdoku.org).
- [X] Check that there is not an existing ticket for this question, and that it is not related to an existing ticket.
- [X] If you aren't sure whether something is a bug, create a bug report anyway (instead of using this form).
- [X] Write a concise title for this ticket in the field above.

### Question type

- [X] Using Houdoku
- [X] Clarification on existing documentation
- [X] Development
- [ ] Other

### What is your question?

When reading offline using the downloaded chapters are not in order when reading offline is this a bug or It really is like that like in Hakuneko.

### Additional information

[main.old.log](https://github.com/xgi/houdoku/files/7192360/main.old.log)
[renderer.log](https://github.com/xgi/houdoku/files/7192362/renderer.log)
[renderer.old.log](https://github.com/xgi/houdoku/files/7192363/renderer.old.log)
[main.log](https://github.com/xgi/houdoku/files/7192364/main.log)
These are the logs if you need them or anything. :D

**Comment by xgi** [comment]
Can you clarify which part is not in order? Do you mean that the pages in the chapter are in the wrong order, or that the chapter directories aren't in order? (or something else)

If it's about directories not being in order, that's expected -- the directories will have random names that aren't necessarily in order.

**Comment by f-ate** [comment]
The pages in a chapter after being downloaded are not in order but as soon as we delete the download and reopen the chapter they again get in order for ex -  BERSERK chapter 236 when downloaded from man
gadex, mangalife, mangasee shows the pages in that chapter out of order like this ![Screenshot from 2022-02-08 08-09-00](https://user-images.githubusercontent.com/97509895/152907870-a5ea73e1-b163-4dbd-8f59-84c7db977c88.png) but as soon as we delete the chapter the pages become ordered again like this
![Screenshot from 2022-02-08 08-09-49](https://user-images.githubusercontent.com/97509895/152908027-3511f30d-ba94-40ab-ac41-8e386a9c24e2.png)
