### ISSUE TITLE
Hide scrollbar when reading a chapter

### ISSUE THREAD

**Issue by PeyonManuel** [xgi/houdoku#78]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

I usually dont like to know where i am in a story, if its in the middle or about to finish, it could be an easy toggle in the settings.

**Comment by xgi** [comment]
Added with #81, thanks!
