### ISSUE TITLE
Pixel perfect fit

### ISSUE THREAD

**Issue by PeyonManuel** [xgi/houdoku#79]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

A fit option that fits the image 1:1 with the screen pixels, like manga4life does it automatically.

**Comment by xgi** [comment]
I'm not sure what "1:1 with the screen pixels" means. How is this different from fullscreening the Houdoku window?

**Comment by PeyonManuel** [comment]
Like, if the image is say 890px wide, the image would fit in 890 pixels wide on the screen. With this you dont get natural antialiasing and it looks sharper.

**Comment by xgi** [comment]
Got it, that makes sense. I think some other readers refer to it as "original size". I think I still have work to do on how fitting works in general, but I can look into adding this mode.

**Comment by PeyonManuel** [comment]
Yeah "original size" sounds better, wasnt sure how to say this idea that i had in my mind lol.

**Comment by xgi** [comment]
Been a while, but I've overhauled the reader with v2.7.0, and there's now a separate toggle for whether to stretch pages (along with the fit options). Thanks!

**Comment by PeyonManuel** [comment]
Thank you for this reader and support for it!
