### ISSUE TITLE
Decimal point scoring for anilist

### ISSUE THREAD

**Issue by PeyonManuel** [xgi/houdoku#80]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

Score with decimals or maybe even all the other scoring systems that anilist has.

**Comment by xgi** [comment]
I can add AniList's other scoring formats, thanks for the suggestion!

**Comment by xgi** [comment]
As of #82, the tracker entry will show your scores using your selected format on AniList, and you can update your score with appropriate values for that format.

(caveat: you can't change your score format within Houdoku, and when you change it from AniList you may need to restart Houdoku)
