### ISSUE TITLE
Weird user experience

### ISSUE THREAD

**Issue by ayoub3bidi** [xgi/houdoku#85]
### Acknowledgements

- [X] Check the documentation on [houdoku.org](https://houdoku.org).
- [X] Check that there is not an existing ticket for this question, and that it is not related to an existing ticket.
- [X] If you aren't sure whether something is a bug, create a bug report anyway (instead of using this form).
- [X] Write a concise title for this ticket in the field above.

### Question type

- [X] Using Houdoku
- [ ] Clarification on existing documentation
- [ ] Development
- [ ] Other

### What is your question?

Why the user experience is a little complicated so that i need to read the documentation ?

### Additional information

PS: The only reason i asked this question is because i liked your project and i want it to be better.

**Comment by xgi** [comment]
I appreciate the feedback, but this doesn't give me much info to take action. Are there specific parts of the user experience you think should be improved?

**Comment by ayoub3bidi** [comment]
Well, for example I didn't knew how to download my manga chapters properly without reading the documentation. But what i really wanted to say is that I wanted the user experience to be more simple and easier for the normal users.
