### ISSUE TITLE
issue with chapters with decimal points

### ISSUE THREAD

**Issue by AJO248** [xgi/houdoku#86]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.6.0

### Operating system

Windows 10

### Steps to reproduce

chapters with decimal values like 75.5 are displayed as 75 
example
![image](https://user-images.githubusercontent.com/94214966/142802941-019b2ebb-3930-482b-82cb-8344fe42e05d.png)

### Expected behavior

It should be shown as 75.5

### Actual behavior

It is displayed as 75, it is not included in total chapter count. when reading, the chapters get skipped,

### Additional information

Also a feature to search a manga to track would be nice, as some of them show no data when using trackers, due to additonal text in the title

when using mangadex, many chapters are missing because only manga by a certain group is being displayed

![image](https://user-images.githubusercontent.com/94214966/142805725-5e7390d0-7fb3-40eb-bf87-d01a69ea767a.png)
![image](https://user-images.githubusercontent.com/94214966/142805787-81182836-8c2b-48b8-ae13-99af3d732743.png)

**Comment by xgi** [comment]
I'm not able to reproduce your issue with decimal points. Houdoku does support chapters like this, though there may be an issue with a specific extension -- which one are you using that has that issue?

For your issue about chapters from only one group being displayed, I found that was an issue with the MangaDex extension. If you update the extension to 1.3.0 and refresh the series, you should see every chapter. Note that you can limit which languages to show from the settings tab.

**Comment by AJO248** [comment]
the issues with decimal points are on MangaSee Extension.

The issue with missing chapters were fixed after updating MangaDex.

**Comment by xgi** [comment]
I've fixed this issue with v1.1.1 of the MangaSee/MangaLife extensions. Chapter numbers should now include the decimals. Thanks!
