### ISSUE TITLE
question regarding file format

### ISSUE THREAD

**Issue by generalxid** [xgi/houdoku#87]
### Acknowledgements

- [X] Check the documentation on [houdoku.org](https://houdoku.org).
- [X] Check that there is not an existing ticket for this question, and that it is not related to an existing ticket.
- [X] If you aren't sure whether something is a bug, create a bug report anyway (instead of using this form).
- [X] Write a concise title for this ticket in the field above.

### Question type

- [X] Using Houdoku
- [ ] Clarification on existing documentation
- [ ] Development
- [ ] Other

### What is your question?

In my pc it doesn't recognize cbz cbr files. I tried putting all of them in folders but it still doesn't work. it only displays name of the manga under the list. I can only read if there are images in side the folders.
how do I make it read cbr cbz ?

**Comment by xgi** [comment]
I'm not sure what you mean by "doesn't recognize". If you use the "Select Archive File" button you should be able to select a cbz/cbr file. cbz/cbr are the same as zip/rar, so they are archive files.

**Comment by generalxid** [comment]
I have a folder with comics (they are long strip comics) with each chapter as a cbz file.
![image](https://user-images.githubusercontent.com/93801024/149801907-f4600f23-52a9-42de-814a-1475bc24e3a4.png)
if i add the series by the directory option it doesn't recognize the cbz files and gives the following error.
![image](https://user-images.githubusercontent.com/93801024/149802442-3483bd95-a24e-48ba-b19e-42251bb4f402.png)
if i click on read it just keeps on loading and doesn't start.
![image](https://user-images.githubusercontent.com/93801024/149802682-44c122fc-c757-4f37-afe4-447cf8199d15.png)
If i use the select archive file it doesn't let me select multiple chapters and only one file.
![image](https://user-images.githubusercontent.com/93801024/149803060-98765070-3930-4095-bc48-5ca06172212e.png)
Even if if select one chapter and add it as a series it still gives the same error.
![image](https://user-images.githubusercontent.com/93801024/149803286-719f1953-506a-41c0-8531-c63ed5a395e7.png)
The only way i found to use this application is to extract each chapter as a folder then rename the folders(if i don't rename by adding 0s in the start it jumbles the order) with the images(pages) containing in it.
![1](https://user-images.githubusercontent.com/93801024/149809975-69829810-affd-4982-aa7e-0a484711ea7a.png)
![image](https://user-images.githubusercontent.com/93801024/149810155-8a32c464-4fd7-466e-86b3-13b5513a2828.png)

**Comment by xgi** [comment]
Oh I see; yeah, right now the archive option only supports having the entire series in a CBZ (with chapter directories inside), not chapters with separate CBZ's. I'll add support for this scenario.

Thanks as well for the details + screenshots.

**Comment by generalxid** [comment]
Oh now I realized how to use the archive option. If is it possible could you also add the logical sorting option it jumbles the numbering of the chapter if it is in 1,2,3,4 instead of 001,002,003 format. Thanks.

**Comment by xgi** [comment]
With #91 I've changed how archive support works in Houdoku. Previously the entire series had to be contained in an archive (zip/cbz/rar/cbr). Now users will always select a directory for the series, but that directory can contain chapters as either folders or archives.

I'll update the documentation regarding this when the next version is released.
