### ISSUE TITLE
Better downloading options

### ISSUE THREAD

**Issue by TheInternetUser0** [xgi/houdoku#90]
### Acknowledgements

- [x] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

>You can download chapters by right clicking the tables of chapters on a series page and selecting Download/Download Previous/Download All. You can see what chapters are downloaded by going to the Downloads tab on the left and clicking "My Downloads" -- this will also show you the folder they got downloaded to.

_Originally posted by @xgi in https://github.com/xgi/houdoku/issues/60#issuecomment-895652337_

I know you said this but instead of just "Download Previous", would it be possible to have "Download Next" to download the chapters after it. I mean, it's rare that I want to download the chapters I already read. Instead most people want to download the newest chapters. For example, if I want to download _Martial Peak_ (I'm on ch 800), it's a lot of work to download - say the next 100 chapters. So having something like "Download Next 10/100" is an easier option.

Unrelated but a Discord server would make _this_ easier too.

**Comment by xgi** [comment]
Good suggestion, I'll add this. I actually thought I added a "Download X" button a while ago, but apparently not! I can probably add a "Download Unread" button on there too.

As for a Discord -- I really don't want to have to do moderation work, especially in a much more informal medium. Closest I might get is opening [GitHub Discussions](https://docs.github.com/en/discussions).

**Comment by TheInternetUser0** [comment]
> I can probably add a "Download Unread" button on there too.

This would be great and covers most needs but a "Download Next {some number} Chapters" is better for longer series. Even without it cool addition 👍

> I really don't want to have to do moderation work, especially in a much more informal medium.

Well, there are a lot of people who would do it for you if you want. It's just about trust. And an informal medium makes people at ease to ask. But nevermind that,  GitHub Discussions sounds epic too

If this app keeps improving like this, it might replace my YACReader + HakuNeko + Going-to-browser-to-manually-update setup XD. So keep up the work!

**Comment by xgi** [comment]
Added improved download options with #95. Next release will be sometime next week. Thanks!
