### ISSUE TITLE
The pages in downloaded chapters become out of order

### ISSUE THREAD

**Issue by f-ate** [xgi/houdoku#92]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

"2.7.1"

### Operating system

"Windows 10, Ubuntu 21.10"

### Steps to reproduce

The pages in a chapter after being downloaded are not in order but as soon as we delete the download and reopen the chapter they again get in order for ex -  BERSERK chapter 236 when downloaded from man
gadex, mangalife, mangasee shows the pages in that chapter out of order like this ![Screenshot from 2022-02-08 08-09-00](https://user-images.githubusercontent.com/97509895/152907870-a5ea73e1-b163-4dbd-8f59-84c7db977c88.png) but as soon as we delete the chapter the pages become ordered again like this
![Screenshot from 2022-02-08 08-09-49](https://user-images.githubusercontent.com/97509895/152908027-3511f30d-ba94-40ab-ac41-8e386a9c24e2.png)

### Expected behavior

The pages in chapter should have been in order after being downloaded.

### Actual behavior

The downloaded pages in chapter are not in order but gets in order when we delete the downloaded chapter or read directly without downloading the chapter. I even checked webtoons and the downloaded chapters show wrong order of pages.

### Log files

-Ubuntu 21.10 log files: 
[main.log](https://github.com/xgi/houdoku/files/8020330/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/8020331/renderer.log)
 

### Additional information

I actually like the scrolling of this software very much it is very smooth and that is the main reason i decided to use this but as my internet is not stable i have to download and read mangas as the loading times are long. If possible i would appreciate if you could look into this problem thanks.

**Comment by xgi** [comment]
Found out what happened: the images from the filesystem were being sorted alphabetically, e.g. `1.jpg, 10.jpg, 11.jpg` rather than the expected `1.jpg, 2.jpg, 3.jpg`. Fixed this with #96. I'll publish an updated release sometime next week.

Thanks for the detailed description and logs, it was very helpful!

**Comment by f-ate** [comment]
All Thanks goes to you for such an amazing software keep up the good work.
