### ISSUE TITLE
A option to go full-screen mode?

### ISSUE THREAD

**Issue by Kayizoku** [xgi/houdoku#93]
### Acknowledgements

- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] Create one ticket per feature. Feel free to create multiple tickets.
- [X] If this is an extension-related request, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Feature details

If you press F11 now for fullscreen it's not hiding the whole top of the app. It would be really neat to have that option. As an addition, it would be great to control if you want to hide or show the top navigation bar that displays information about the current file-

![image](https://user-images.githubusercontent.com/28716224/153026467-e4a422ef-570d-407b-b21c-513d9af4199e.png)

**Comment by xgi** [comment]
There are some oddities/things that need to be worked out to make this possible (e.g. right now, internally, the viewer is set to 100% of the height of the window, but there's also padding at the top so it doesn't overlap the header).

I can't say this is my top priority, but I'll get to it if I can!

**Comment by korason7117** [comment]
> There are some oddities/things that need to be worked out to make this possible (e.g. right now, internally, the viewer is set to 100% of the height of the window, but there's also padding at the top so it doesn't overlap the header).
> 
> I can't say this is my top priority, but I'll get to it if I can!

Should be your top priority...
that is if you're a fan of manga/hua/hwa. for me it doesn't make sense for full screen option to not be available.
Making the app more beautiful is just unnecessary.. it already feels beautiful enough, pls just make full screen possible
I had to uninstall the app only because it was missing this important feature. I'll wait patiently for this feature to be implemented.

**Comment by xgi** [comment]
With #124, I've added:
* Going fullscreen will now hide the titlebar on all pages.
* On the reader, pressing `m` (configurable in settings) will hide the menu/control bar.

Thanks!
