### ISSUE TITLE
CBZ files are not being loaded correctly

### ISSUE THREAD

**Issue by Kayizoku** [xgi/houdoku#94]
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.7.1

### Operating system

Windows 10

### Steps to reproduce

Loading a folder that contains a CBZ file or loading it directly as an archive. Neither options works and does not display images.

### Expected behavior

Should show images.

### Actual behavior

Does not show images.

**Comment by xgi** [comment]
This was address in #87, it'll be updated in the next release.
